In [4]:
import pandas as pd

In [6]:
df=pd.read_csv('Police Data.csv')

In [7]:
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,01/02/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/06/2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/06/2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12/06/2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12/07/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/07/2012,0:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [9]:
df.head(11)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,01/02/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
5,3/23/2005,9:45,NaN,M,1982.0,23.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
6,04/01/2005,17:30,NaN,M,1969.0,36.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
7,06/06/2005,13:20,NaN,F,1986.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
8,7/13/2005,10:15,NaN,M,1970.0,35.0,Black,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
9,7/13/2005,15:45,NaN,M,1970.0,35.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
10,7/13/2005,16:20,NaN,M,1979.0,26.0,Asian,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [10]:
df.tail(11)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
65524,12/06/2012,15:06,NaN,F,1974.0,38.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65525,12/06/2012,15:09,NaN,M,1980.0,32.0,White,Equipment/Inspection Violation,Equipment,False,NaN,N/D,False,0-15 Min,False
65526,12/06/2012,15:22,NaN,M,1982.0,30.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65527,12/06/2012,15:26,NaN,F,1981.0,31.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65528,12/06/2012,15:39,NaN,M,1987.0,25.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65529,12/06/2012,16:00,NaN,M,1994.0,18.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65530,12/06/2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/06/2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12/06/2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12/07/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/07/2012,0:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [11]:
df.shape

(65535, 15)

In [45]:
df.isnull().sum()

stop_date                 0
stop_time                 0
country_name          65535
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

In [106]:
df2=df.fillna('nothing')

In [107]:
df2.isnull().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
dtype: int64

In [163]:
df3=df2[['driver_gender']][df2['violation']=='Speeding']

In [164]:
df3['driver_gender'].value_counts()

M          25517
F          11686
nothing        1
Name: driver_gender, dtype: int64

In [165]:
differencebetweenmaleandfemale=25517-11686

In [166]:
differencebetweenmaleandfemale

13831

In [167]:
df2['driver_gender'].value_counts()

M          45164
F          16310
nothing     4061
Name: driver_gender, dtype: int64

In [168]:
df4=df2['stop_duration'].value_counts()

In [169]:
df4.max

<bound method Series.max of 0-15 Min     47379
16-30 Min    11448
nothing       4060
30+ Min       2647
2                1
Name: stop_duration, dtype: int64>

In [170]:
df2['violation'].value_counts()

Speeding               37204
Moving violation       11926
Equipment               6516
nothing                 4060
Other                   3583
Registration/plates     2243
Seat belt                  3
Name: violation, dtype: int64

In [181]:
df2['driver_age'][df2['violation']=='Speeding'].value_counts()

21.0    1902
22.0    1883
20.0    1856
23.0    1727
24.0    1668
        ...
86.0       3
84.0       3
88.0       2
83.0       1
15.0       1
Name: driver_age, Length: 73, dtype: int64

In [182]:
df2['driver_age'][df2['violation']=='Moving violation'].value_counts()

23.0    452
22.0    445
21.0    438
20.0    405
24.0    400
       ...
81.0      2
86.0      2
82.0      1
83.0      1
85.0      1
Name: driver_age, Length: 72, dtype: int64

In [183]:
df2['driver_age'][df2['violation']=='Equipment'].value_counts()

23.0    385
21.0    374
22.0    370
20.0    348
24.0    329
       ...
74.0      1
76.0      1
79.0      1
80.0      1
81.0      1
Name: driver_age, Length: 66, dtype: int64

In [212]:
df2['driver_age'][df2['violation']=='Other'].value_counts()

48.0       116
nothing    106
45.0       101
44.0       100
50.0        99
          ...
69.0         2
82.0         1
86.0         1
75.0         1
16.0         1
Name: driver_age, Length: 66, dtype: int64

In [213]:
df2['driver_age'][df2['violation']=='Registration/plates'].value_counts()

22.0       129
26.0       114
24.0       109
20.0       106
25.0        99
23.0        99
21.0        96
27.0        93
28.0        77
29.0        74
19.0        69
32.0        69
30.0        60
35.0        60
37.0        56
40.0        53
31.0        51
34.0        51
33.0        49
39.0        46
43.0        45
45.0        44
41.0        44
36.0        43
42.0        41
38.0        40
18.0        38
46.0        36
51.0        33
44.0        32
49.0        27
52.0        27
50.0        26
47.0        25
48.0        24
53.0        19
54.0        19
56.0        18
55.0        17
58.0        14
59.0        13
60.0         9
17.0         8
57.0         7
63.0         6
16.0         5
62.0         4
61.0         3
66.0         3
nothing      3
64.0         2
65.0         2
74.0         1
68.0         1
69.0         1
70.0         1
72.0         1
73.0         1
Name: driver_age, dtype: int64

In [257]:
df['driver_age'].mean()

34.14898412491017

In [323]:
df2['is_arrested'].value_counts()

False      59215
nothing     4060
True        2260
Name: is_arrested, dtype: int64

In [324]:
df2['drugs_related_stop'].value_counts()

False    65017
True       518
Name: drugs_related_stop, dtype: int64